# Generated by Django 4.1 on 2022-08-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_gear_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('gear', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.gear')),
            ],
        ),
    ]
